### ISSUE TITLE
FR: Add support for entry locations

### ISSUE THREAD

**Issue by benfeather** [towardstudio/asset-locations#5]
Hi, just wanted to say this plugin has been extremely useful, so we appreciate your work.

Do you have any plans to extend the functionality to work with entries? For example, we could add the locations field to an entry that is used as a category/tag and see a list of entries that link to it.

This may be outside the scope of this plugin, but the table-style locations field would be perfect for this.

**Comment by DowleyDeveloped** [comment]
Hi,

Really glad the plugins been great for you!

No future plans currently, however I think the [Related Entries](https://plugins.craftcms.com/related-elements?craft5) plugin might actually be what you're after?

**Comment by benfeather** [comment]
We've tried the Related Entries plugin and it does work well, but we'd prefer not to have the list in the sidebar as when have categories linked to 100's of other entries. 

No worries though, thanks again for the great plugin.

**Comment by DowleyDeveloped** [comment]
Ah I see. 

You’re welcome!
